language: python
sudo: false
cache:
  directories:
  - container
matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.5'
  - os: linux
    python: pypy-5.3.1
  - os: osx
    language: generic
    env: PYTHON=python PIP=pip
    osx_image: xcode8
  - os: osx
    language: generic
    env: PYTHON=python3 PIP=pip3
    osx_image: xcode8
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/python/setup.py -e bash -p /dev/stdout)
script:
- polysquare_run check/python/check.py
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/python/coverage.py
before_deploy:
- polysquare_run deploy/python/deploy.py
deploy:
  provider: pypi
  user: Sam.Spilsbury
  password:
    secure: gxIKURqPoY612RPDl32myi0UYuH78xuwC5808M/mq/7T7mjOP8MD0DW2BhAMUxKJ3gUHYm7SY4ZsS0q4q46Wg8huId8kij5HxLT6hLi5qogqMEkAhTbE53yjcXYOf3Tvo4wtL3By2IhzMUv6dJf16cTSKQUz9FfLaaVuAB8BjtqFiR9gYZY5+rp24uS1bJGCo/AXxCMi+p/3n7zK5bpFmtUII8t+9MqRpOJMH1TUAx1Yk5Jbq6gspqdm4+r8qDgJVQ8HUAaInuMDvzPuD09islrRxiQKa477YvQgTOIpD/f0mTWDe1ics5QEpWYAq5pBNdP4wyrP2lvLJRKsmly4Eud5gNvHNXKgoaaZ2chUwS2IXGR6jCxzn7PrxhQW5Zd6/Z/GbS4VuIxXVG8Y62VozTjaoOSn2fPdYdYmWuQIOCNJF648dwO4tTdZFEgPRAtVbUH6vPQFFXXlaP9SK5vaQXLaLEgIkrHuRhu+Gc9dx4knFrT90drIogy+QrnMVd+03mpy8S8bBYOxTtWvxIQJUAytxSHN9ndxzObD5YnKwT1hpr/5BXH6qwvOonfTl4T1Q4vYwMOIRLbq6TP34s3TivAwJtsreM8tf14LUxBgDswj+v1b9J2P/+XoIROfHgP97+D7uZW8Qc53r6eV3/ZPeM6Cma5Wlnc0gWlh8TcIyJM=
  on:
    repo: polysquare/python-parse-shebang
env:
  global:
    secure: dZ5yt0RR7eJ7kEmPEasnq43Dp3ztrDLervoobDCsGnROGmfupb7k/oWI6y23OyH9ALE2hdbtgwHTn1DlqM8q6zq5/bTmmIXcz6ru+yWhmNQPoAcNwdSEfXL+4YCf72wr7BcZYS3AsdTm0e212s7zUoNUQGtnZKKLs1k/8msuP8kEUwkdDVYWLcqwZ7bIZLlpLx0nMw81uW5m8fj+4IB6l/WyWK/40Q1y0vrQszlzl/YzYtImUpBh/xvYluWX/5s2N+oAT71a4O9XjX8Je2QR8+0xkw9MtWRa1AXBGqMZ+myCbca9hqR/XAaAUBU9pzhwXncpLt9Xtt/avFL1OPQqDQoyQX5MMGONzdWHYZWXSUEj0Q7y0NAD22JTJh8Vk8QrwVxCEGyGFwCY6vosj3NtloIB+pVgPiYc2zJFzfazjgTYidbyQpRcxrVbIk1USYXii9DoskopIYZJUIXhME0EPjbVY4TGPs7Ur5+aQP3jFW2yUooeTshXGqASzMSKyI59c86n/NcFY/wFfWNXTGGc8RYCBCY/edXylTAr0MuoJu7iGWGsF4IuIM+sVjNLjON2gdHy3Sfm9WNUJmBe8jNNbYI20rK/lfsw25clF3tzPrBHff2yFTMOnBiXhoQTIa2u2Lecrv1zWRxkK7e1hAjuHxxcGPGFdyl84TROpnLNwoY=
